<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Mascota>
 */
class GameFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $gameNames = [
            'Dragon Realm', 'Shadow Quest', 'Mystic Legends', 'Solar Strike', 'Phantom Horizon', 'Steel Warriors', 
            'Neon Dreams', 'Eternal Battle', 'Lunar Chronicles', 'Cyber Odyssey', 'Inferno Dawn', 'Crystal Kingdom', 
            'Cosmic Drift', 'Arcane Expedition', 'Celestial Forge', 'Dark Tides', 'Ember Knights', 'Thunder Strike', 
            'Titan’s Wrath', 'Lost Realms', 'Neon Horizon', 'Savage Skies', 'Abyss Chronicles', 'Phoenix Reborn', 
            'Forgotten Lands', 'Solar Forge', 'Arcane Rites', 'Bloodstone Saga', 'Frostbound', 'Eternal Flames', 
            'Venom’s Edge', 'Infinite Void', 'Iron Quest', 'Divine Clash', 'Apex Legends', 'Iron Wolves', 
            'Zenith Battle', 'Titan Rift', 'Starbound Warriors', 'Twilight Kingdom', 'Ember Shadows', 'Nexus Heroes', 
            'Forbidden Path', 'Shattered Stars', 'Thunder Quest', 'Celestial Trials', 'Iron Reign', 'Galaxy Raiders', 
            'Spirit War', 'Dawnbound', 'Shining Forge', 'Phantom Legacy', 'Crimson Odyssey', 'Infinite Strife', 
            'Legacy of Shadows', 'Iron Souls', 'Phantom Warriors', 'Arcane Skies', 'Shadow Chronicles', 'Eternal Bond', 
            'Forgotten Sins', 'Mystic Realms', 'Cyber Hunter', 'Pixel Adventure', 'Battleforge', 'Lost Horizon', 
            'Celestial Gate', 'Enigma’s Path', 'Horizon Call', 'Shining Quest', 'Frozen Path', 'Mystic Tide', 
            'Thunder Legends', 'Crimson Shadows', 'Galactic Odyssey', 'Steel Warlords', 'Soulbound', 'Phoenix Valor', 
            'Shadowfire', 'Frost Knights', 'Forgotten Depths', 'Savage Lands', 'Titan Bound', 'Crystal Echoes', 
            'Ember Saga', 'Shattered Forge', 'Celestial Dawn', 'Mythic Skies', 'Iron Echoes', 'Solar Tide', 
            'Nexus Reborn', 'Silent Destiny', 'Arcane Legends', 'Shadowbound', 'Phantom Tide', 'Celestial Fire', 
            'Twilight Echo', 'Mystic Clans', 'Frostfire', 'Savage Saga', 'Phoenix Echoes', 'Legend’s Path', 
            'Legacy Forge', 'Shadowbound', 'Celestial Fury', 'Steel Saga', 'Abyss Rising', 'Darkfire Reign', 
            'Ironbound', 'Cosmic Skies', 'Apex Knights', 'Celestial Rift', 'Mythic Path', 'Shining Valor', 
            'Ironborn', 'Shattered Tide', 'Frostborn', 'Shadow Saga', 'Lost Skies', 'Venom Forge', 'Mythic Chronicles', 
            'Iron Rebirth', 'Thunderbound', 'Savage Reign', 'Dark Echoes', 'Celestial Saga', 'Mystic Echo', 
            'Ironheart', 'Spiritbound', 'Frozen Echoes', 'Eternal Skies', 'Phoenix Rising', 'Lost Echo', 
            'Celestial Reign', 'Abyss Saga', 'Soulbound Warriors', 'Thunder Echoes', 'Legend’s Call', 'Iron Legacy', 
            'Darkfire Legends', 'Arcane Echoes', 'Twilight Rebirth', 'Phantom Reign', 'Solar Knights', 'Savage Valor', 
            'Thunderfire', 'Shattered Path', 'Mythic Quest', 'Arcane Reign', 'Iron Tide', 'Frostfire Saga', 
            'Nexus Legends', 'Celestial Strike', 'Mythic Knights', 'Phoenix Saga', 'Soulfire', 'Mystic Fire', 
            'Venom Rebirth', 'Iron Forge', 'Darkfire Call', 'Thunder Saga', 'Celestial Path', 'Arcane Bond', 
            'Eternal Saga', 'Soulbound Knights', 'Phoenix Reign', 'Celestial Echo', 'Abyss Legends', 'Thunder Skies', 
            'Spirit Reborn', 'Phoenix Skies', 'Lost Echoes', 'Twilight Reign', 'Celestial Knights', 'Iron Strike', 
            'Dark Saga', 'Frozen Warriors', 'Iron Reign', 'Mystic Forge', 'Savage Call', 'Eternal Knights', 
            'Iron Reign', 'Soulbound Saga', 'Phoenix Path', 'Shattered Skies', 'Celestial Bond', 'Thunder Knights', 
            'Frostfire Echoes', 'Mystic Reign', 'Phoenix Rebirth', 'Celestial Quest', 'Arcane Knights', 'Abyss Bound', 
            'Thunder Reign', 'Celestial Fire', 'Darkfire Skies', 'Ironborn Saga', 'Soulfire Rebirth', 'Frost Knights', 
            'Celestial Fury', 'Abyss Call', 'Twilight Saga', 'Mythic Reign', 'Savage Rebirth', 'Phoenix Forge', 
            'Celestial Chronicles', 'Frozen Echo', 'Iron Quest', 'Mystic Path', 'Spirit Reign', 'Celestial Echoes', 
            'Shadowfire Saga', 'Thunderbound Warriors', 'Iron Warriors', 'Celestial Bound', 'Spirit Knights', 
            'Phoenix Legends', 'Ironborn Reign', 'Frostfire Reign', 'Mythic Forge', 'Celestial Warriors', 
            'Thunder Rebirth', 'Arcane Fury', 'Darkfire Knights', 'Lost Reign', 'Celestial Echo', 'Spirit Call', 
            'Frozen Fire', 'Phoenix Knights', 'Iron Echoes', 'Eternal Reign', 'Darkfire Path', 'Ironbound Call', 
            'Celestial Path', 'Spirit Echo', 'Phoenix Rebirth', 'Lostfire', 'Ironborn Call', 'Mythic Knights', 
            'Celestial Call', 'Frostfire Warriors', 'Thunder Skies', 'Celestial Saga', 'Soulbound Path', 'Phoenix Quest',
        ];
        $gameImages = [
            "https://picsum.photos/id/1011/200/300",
            "https://picsum.photos/id/1025/200/300",
            "https://picsum.photos/id/1031/200/300",
            "https://picsum.photos/id/1032/200/300",
            "https://picsum.photos/id/1033/200/300",
            "https://picsum.photos/id/1035/200/300",
            "https://picsum.photos/id/1038/200/300",
            "https://picsum.photos/id/1040/200/300",
            "https://picsum.photos/id/1044/200/300",
            "https://picsum.photos/id/1045/200/300",
            "https://picsum.photos/id/1048/200/300",
            "https://picsum.photos/id/1049/200/300",
            "https://picsum.photos/id/1052/200/300",
            "https://picsum.photos/id/1053/200/300",
            "https://picsum.photos/id/1055/200/300",
            "https://picsum.photos/id/106/200/300",
            "https://picsum.photos/id/1062/200/300",
            "https://picsum.photos/id/1063/200/300",
            "https://picsum.photos/id/1067/200/300",
            "https://picsum.photos/id/107/200/300",
            "https://picsum.photos/id/1070/200/300",
            "https://picsum.photos/id/1084/200/300",
            "https://picsum.photos/id/1085/200/300",
            "https://picsum.photos/id/1087/200/300",
            "https://picsum.photos/id/1089/200/300",
            "https://picsum.photos/id/109/200/300",
            "https://picsum.photos/id/110/200/300",
            "https://picsum.photos/id/1101/200/300",
            "https://picsum.photos/id/1108/200/300",
            "https://picsum.photos/id/111/200/300",
            "https://picsum.photos/id/112/200/300",
            "https://picsum.photos/id/113/200/300",
            "https://picsum.photos/id/114/200/300",
            "https://picsum.photos/id/115/200/300",
            "https://picsum.photos/id/116/200/300",
            "https://picsum.photos/id/117/200/300",
            "https://picsum.photos/id/118/200/300",
            "https://picsum.photos/id/119/200/300",
            "https://picsum.photos/id/120/200/300",
            "https://picsum.photos/id/121/200/300",
            "https://picsum.photos/id/122/200/300",
            "https://picsum.photos/id/123/200/300",
            "https://picsum.photos/id/124/200/300",
            "https://picsum.photos/id/125/200/300",
            "https://picsum.photos/id/126/200/300",
            "https://picsum.photos/id/127/200/300",
            "https://picsum.photos/id/128/200/300",
            "https://picsum.photos/id/129/200/300",
            "https://picsum.photos/id/130/200/300",
            "https://picsum.photos/id/131/200/300",
            "https://picsum.photos/id/132/200/300",
            "https://picsum.photos/id/133/200/300",
            "https://picsum.photos/id/134/200/300",
            "https://picsum.photos/id/135/200/300",
            "https://picsum.photos/id/136/200/300",
            "https://picsum.photos/id/137/200/300",
            "https://picsum.photos/id/138/200/300",
            "https://picsum.photos/id/139/200/300",
            "https://picsum.photos/id/140/200/300",
            "https://picsum.photos/id/141/200/300",
            "https://picsum.photos/id/142/200/300",
            "https://picsum.photos/id/143/200/300",
            "https://picsum.photos/id/144/200/300",
            "https://picsum.photos/id/145/200/300",
            "https://picsum.photos/id/146/200/300",
            "https://picsum.photos/id/147/200/300",
            "https://picsum.photos/id/148/200/300",
            "https://picsum.photos/id/149/200/300",
            "https://picsum.photos/id/150/200/300",
            "https://picsum.photos/id/151/200/300",
            "https://picsum.photos/id/152/200/300",
            "https://picsum.photos/id/153/200/300",
            "https://picsum.photos/id/154/200/300",
            "https://picsum.photos/id/155/200/300",
            "https://picsum.photos/id/156/200/300",
            "https://picsum.photos/id/157/200/300",
            "https://picsum.photos/id/158/200/300",
            "https://picsum.photos/id/159/200/300",
            "https://picsum.photos/id/160/200/300",
            "https://picsum.photos/id/161/200/300",
            "https://picsum.photos/id/162/200/300",
            "https://picsum.photos/id/163/200/300",
            "https://picsum.photos/id/164/200/300",
            "https://picsum.photos/id/165/200/300",
            "https://picsum.photos/id/166/200/300",
            "https://picsum.photos/id/167/200/300",
            "https://picsum.photos/id/168/200/300",
            "https://picsum.photos/id/169/200/300",
            "https://picsum.photos/id/170/200/300",
            "https://picsum.photos/id/171/200/300",
            "https://picsum.photos/id/172/200/300",
            "https://picsum.photos/id/173/200/300",
            "https://picsum.photos/id/174/200/300",
            "https://picsum.photos/id/175/200/300",
            "https://picsum.photos/id/176/200/300",
            "https://picsum.photos/id/177/200/300",
            "https://picsum.photos/id/178/200/300",
            "https://picsum.photos/id/179/200/300",
            "https://picsum.photos/id/180/200/300",
            "https://picsum.photos/id/181/200/300",
            "https://picsum.photos/id/182/200/300",
            "https://picsum.photos/id/183/200/300",
            "https://picsum.photos/id/184/200/300",
            "https://picsum.photos/id/185/200/300",
        ];
        return [
            'nombre' => $this->faker->randomElement($gameNames),
            'descripcion' => $this->faker->text(),
            'fecha_lanzamiento' => $this->faker->date(),
            'categoria_id' => $this->faker->numberBetween(1, 7),
            'imagen' => $this->faker->randomElement($gameImages),
        ];
    }}  